spring:
  profiles:
    active: ${APP_PROFILE:json}
  main:
    banner-mode: off
  server:
    port: ${PORT:8080}

carrent:
  json:
    users-file: users.json
    vehicles-file: vehicles.json
    rentals-file: rentals.json
    categories-file: categories.json

---
spring:
  config:
    activate:
      on-profile: json
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: jdbc
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: jpa
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true